### ISSUE TITLE
City of Sacramento: Data Visualization of 2015-16 Budget

### ISSUE THREAD

**Issue by roughani** [code4sac/projects#2]
On May 6, 2015, the City of Sacramento expressed interest in us producing a data visualization tool based on their [2015-16 Fiscal Year Proposed Budget](http://data.cityofsacramento.org/datastreams/92727/city-of-sacramento-proposed-budget-fiscal-year-201516/). See [Open Spending](https://openspending.org/), [Open Budget Oakland](http://openbudgetoakland.org/), and the [U.S. Budget Visualization](http://solomonkahn.com/us_budget/) for examples. 

Please note that there may be an updated dataset based on the 2015-16 Approved Budget that will go into effect on July 1, 2015. [Learn more about the city's budget process](http://portal.cityofsacramento.org/Finance/Budget).

**Comment by rjulian** [comment]
We discussed tonight that this project will be the focus of the June 24th meetup! Joel discussed the possibility of doing it in R and Shiny.

**Comment by joelrip** [comment]
A number of the fields/values in the city budget data are unclear and could use clarification from the city to help people who are trying to understand/visualize them.
- How should we think about the Object Class titled "Labor and Supply Offset"? Is it appropriate to include these negative amounts when calculating the size of a department's budget?
- What is the large negative amount in the "Non-Appropriated" department?

I'm sure other questions will come to me, but just trying to get them down so we can ask Mrudul.

**Comment by joelrip** [comment]
When looking at the City Attorney budget, there is no way to separate out litigation expenses from other expenses. What categorization is this? Can we get this?

Also: we should really have the FTEs available to us as well.
