### ISSUE TITLE
Bike Count App

### ISSUE THREAD

**Issue by wleddy** [code4sac/projects#6]
My name is Bill Leddy and I'm a volunteer with the Sacramento Area Bicycle Advocates (SABA). I would like to pitch a project to CfS to reimagine as an open source project, a mobile app that I created a few years ago. 

SABA participants in a national bike and pedestrian traffic count which happens four times a year. The data is used to help support the efforts of bike/Ped advocates in their efforts to improve infrastructure and access for all modes of active transportation. 

I'm no longer in a position to update and continue development of the app and I'm hoping that CfS will feel that this is a project worthy of your efforts. I'm eager to meet with your group to answer any questions you have and describe the goals more fully. Here is a link to a [Dropbox Share](https://www.dropbox.com/sh/cr8bffsr30zm5b8/AABJjX5teCTj4EMn_wgUX2nla?dl=0) that includes a Scope of Work document with more details. 

Bill Leddy
bill@williesworkshop.net
916-601-6131

**Comment by rjulian** [comment]
Hey Bill,

We met at Concerts in the Park a few weeks back! We just finished up our budget hack and have content for our next meeting planned, but I'll bring up getting people to work on this at the next meeting. Thanks so much for the link to the share!

**Comment by wleddy** [comment]
Thanks Richard. I look forward to to hearing from you. 

Regards,
    Bill Leddy

**Comment by roughani** [comment]
Hi @wleddy,

Great to hear from you again. One question I have is whether you're interested in being the product manager on this project or if your preference is to hand off the entire project to us. Our most successful projects have a champion who is committed to leading a project from beginning to end. Otherwise, it's very difficult for us to keep focused with so many other balls in the air. And if you're not available to be the product manager, maybe there's someone who you can recommend?

**Comment by wleddy** [comment]
If be happy to act as product manager on the project. 

I look forward to presenting the project to the group. 

Regards,
    Bill Leddy

**Comment by wleddy** [comment]
Richard,

When is the next Code for Sac meeting? I'd really like to meet to pitch my Bike Counting project.

Regards,
    Bill Leddy

**Comment by rjulian** [comment]
Hey Bill,

Can you make it on Wednesday?

I'm currently working on a project proposal for it. I realize there's no 
such open source bike/walk/general count application out there. I'm 
thinking of doing it in Phonegap (since I have that environment already 
loaded and ready).

**Comment by wleddy** [comment]
Wednesday would be great. What time?
 From the very little I know of Phone Gap I thought that it would be something to look at. Sounds like a great idea to me. 
Regards,
    Bill Leddy

**Comment by rjulian** [comment]
Wednesday at 7:30PM at the Hacker Lab would be when we meet. It'll just 
be a core team meeting, so you won't have to do a formal pitch, just 
essentially go over the project. I'll hope to have something ready by 
then as well.

**Comment by wleddy** [comment]
Hi Richard,

Great talking with all of you at Hacker Lab tonight. 

My app web site is at http://bikeandwalk.org

Here are some links to additional info on the bike and walk app. 

In the app stores:
Android: looks like it was removed from google play. I'll try to get that fixed. 
Apple: http://itunes.apple.com/us/app/bike-and-walk/id524254162?ls=1&mt=8
As I demoed, it works ok in iOS 7 but in 8 you can't create a report due to the select widget issue. 

The Dropbox share is at: 
https://www.dropbox.com/sh/cr8bffsr30zm5b8/AABJjX5teCTj4EMn_wgUX2nla?dl=0

The National Bike and Ped. Documentation Project is at:
http://bikepeddocumentation.org
Detailed instructions and PDFs of the count forms are in the downloads section.

Here is the Bicycle Count Clearinghouse site created by the Luskin Ctr. at UCLA:
http://www.bikecounts.luskin.ucla.edu
Their code _may_ be available to fork as open source. I have a contact there and can follow up when/if we get to that stage. 

Regards,
    Bill Leddy

**Comment by roughani** [comment]
Project now under active development. Adding to our projects Google Spreadsheet and closing this issue.

EDIT: [Project repo](https://github.com/code4sac/bikecounter/issues)
